// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-I3tqh4CSfYHtizBcE3H17oW5JIl2pU',
    appId: '1:1006234958062:web:8a41b960a495115d0adbff',
    messagingSenderId: '1006234958062',
    projectId: 'softmed-2fe32',
    authDomain: 'softmed-2fe32.firebaseapp.com',
    storageBucket: 'softmed-2fe32.firebasestorage.app',
    measurementId: 'G-YGJ6BB00BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsAwmNVDi7PEHMTJN8XBWzeJ7h4MAmlsU',
    appId: '1:1006234958062:android:768497741ce0624a0adbff',
    messagingSenderId: '1006234958062',
    projectId: 'softmed-2fe32',
    storageBucket: 'softmed-2fe32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4GAE55mP1FezOJzH2PF54boTtYwd_bU',
    appId: '1:1006234958062:ios:dd26d5b0e68ba9a30adbff',
    messagingSenderId: '1006234958062',
    projectId: 'softmed-2fe32',
    storageBucket: 'softmed-2fe32.firebasestorage.app',
    iosBundleId: 'com.example.professionalsSeeker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK4GAE55mP1FezOJzH2PF54boTtYwd_bU',
    appId: '1:1006234958062:ios:dd26d5b0e68ba9a30adbff',
    messagingSenderId: '1006234958062',
    projectId: 'softmed-2fe32',
    storageBucket: 'softmed-2fe32.firebasestorage.app',
    iosBundleId: 'com.example.professionalsSeeker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9-I3tqh4CSfYHtizBcE3H17oW5JIl2pU',
    appId: '1:1006234958062:web:73e46fde318fb08c0adbff',
    messagingSenderId: '1006234958062',
    projectId: 'softmed-2fe32',
    authDomain: 'softmed-2fe32.firebaseapp.com',
    storageBucket: 'softmed-2fe32.firebasestorage.app',
    measurementId: 'G-ZK6T96H690',
  );
}
